### ISSUE TITLE
Colour not being detected

### ISSUE THREAD

**Issue by sksamuel** [ajalt/mordant#1]
Using intellij, just a simple function to output some colour.
JDK11, Intellij 2018.3, Mordant 1.2.0

![image](https://user-images.githubusercontent.com/743706/54086692-b597b900-4343-11e9-9b95-4782416dfd2f.png)

![image](https://user-images.githubusercontent.com/743706/54086693-ba5c6d00-4343-11e9-92ac-7e560e72d81d.png)

**Comment by sksamuel** [comment]
System.console() is returning null, but we know intellij can do colour as log4j etc will happily output in colour in intellij.

**Comment by ajalt** [comment]
Yeah, Java's terminal detection is shamefully bad. If you're writing a program where you know you'll always be used interactively, you can force color output: `TermColors(TermColors.Level.TRUECOLOR)`.

For the IntelliJ case specifically, It looks like `idea_rt.jar` gets added to the classpath when running from within the IDE itself, so I think looking for that jar would be a reasonable heuristic. 

There's also the possibility of using JNI to call the native `isatty` function for better detection, although I'm slightly hesitant to add native code to the project. 

What do you think about any of those options?

**Comment by sksamuel** [comment]
Either of the first two. Maybe update docs for the ability to override.
Kolor (another library) doesn't bother with detection as far I can see. 
Rather than look for idea_rt.jar I'd be tempted to see if CommandLineWrapper is on the classpath as that's specifically the class that Intellij uses to launch processes.

**Comment by ajalt** [comment]
Ok, I just released version 1.2.1 which should improve the detection in the IntelliJ console. 

It turned out that neither `idea_rt.jar` nor `CommandLineWrapper` were reliably added to the classpath. I ended up looking at the javaagent used to launch the JNI process and checking for IntelliJ's. 

Let me know if that works, or if you have any ideas on better approaches. You can always still force a color option if you find that detection isn't reliable enough.

**Comment by sksamuel** [comment]
Detects it as None for me I'm afraid. Maybe it works on a Mac but not Linux?

**Comment by sksamuel** [comment]
These are the input args to the management bean on my machine.

```0 = "-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=46407"
1 = "-Dfile.encoding=UTF-8"
2 = "-Duser.country=GB"
3 = "-Duser.language=en"
4 = "-Duser.variant"
5 = "-ea"```

**Comment by sksamuel** [comment]
It might just be me. I'll come back to you shortly.

**Comment by sksamuel** [comment]
I was running the gradle task through intellij, so I don't know if that
counts as "intellij" or not. Probably not.
But it detects it as None regardless, and same for when running through
gradle at the command line.

**Comment by ajalt** [comment]
Yes, an IntelliJ gradle task is the same as running gradle from the command line. I'm pretty sure gradle wraps stdout, so `isatty` returns false. Even if we detect that we're running in gradle, the user can still redirect gradle's stdout, so always using colors inside gradle would be incorrect. Maybe you can configure your gradle task to set the envvar `COLORTERM=truecolor`, which will cause mordant to always use color?

I welcome other suggestions on how to improve the behavior.

**Comment by sksamuel** [comment]
I can do that as you suggest, and that should work fine.

**Comment by ajalt** [comment]
Ok. I'll leave this issue open for now in case someone knows of a better solution.

**Comment by LoganDark** [comment]
IntelliJ's run window has always been shoddy. I'm disappointed that only PyCharm has an actual terminal emulator. I mean come on, you can PYTHON a terminal, but not Java, or C++?!

**Comment by elect86** [comment]
Looking for Idea compatibility, I found this issue..

@sksamuel I tried to clone this project itself and run the `main` under `samples`, it works flawless 

am I missing something?

IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.5616.10, built on February 19, 2020

**Comment by LordMZTE** [comment]
on the windows command line there's also no color and if it is forced then there's just garbage characters.
