### ISSUE TITLE
Support Windows Terminal and CDM colors

### ISSUE THREAD

**Issue by jonnyzzz** [ajalt/mordant#10]
New Windows 10 versions supports ASCII colors (and ASCII links). It would be nice to make the auto-detection to support that too

e.g. https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling

**Comment by ajalt** [comment]
All ANSI colors and hyperlinks should work on windows terminal in the latest alpha release. If you're seeing bugs with that, please provide some more info and we can reopen this issue.

**Comment by jonnyzzz** [comment]
Awesome, thank you so much!
