### ISSUE TITLE
Typo in Borders member TOP_BOTTOM (TOM_BOTTOM)

### ISSUE THREAD

**Issue by Virtlink** [ajalt/mordant#100]
In the `com.github.ajalt.mordant.table.Borders` enum, the member for a top-and-bottom border is called `TOM_BOTTOM` instead of `TOP_BOTTOM`. [Source code](https://github.com/ajalt/mordant/blob/3a344a7ce17e312684e68beb539cb5fe557242d8/mordant/src/commonMain/kotlin/com/github/ajalt/mordant/table/Borders.kt#L14).

**Comment by ajalt** [comment]
Thanks for the report!
