### ISSUE TITLE
Does not properly detect color support in XTerm on Linux

### ISSUE THREAD

**Issue by mikaelstaldal** [ajalt/mordant#113]
XTerm on Linux gets detected as `ANSI16`, even though it supports more colors than that.

**Comment by ajalt** [comment]
I need more information to be able to help. Mordant mostly uses environment variables for ansi detection. You `TERM` envvar is probably set to something like `xterm`, try setting it to `xterm-256` or `xterm-24bit`.

**Comment by ajalt** [comment]
That's a useful envvar. I can add a check for it, but I'd want to look at the actual version number so that we don't use new ansi codes on old versions that don't support it. Do you know which xterm version added 256/truecolor support?

**Comment by mikaelstaldal** [comment]
> That's a useful envvar. I can add a check for it, but I'd want to look at the actual version number so that we don't use new ansi codes on old versions that don't support it.
> 
> It looks like 256 color support was working in [version 122 and truecolor in 331](https://invisible-island.net/xterm/xterm.log.html).

Yes.

**Comment by ajalt** [comment]
@mikaelstaldal I added the xterm version check, give the latest snapshot a try and if it works I'll make a release.

**Comment by mikaelstaldal** [comment]
Here is some documentation on how to do true color in XTerm: https://tintin.mudhalla.net/info/truecolor/

How does Mordant do true color?
