### ISSUE TITLE
Disable glow for progress animation

### ISSUE THREAD

**Issue by cmdjulian** [ajalt/mordant#122]
Is there a way to disable the white glow in the animation? 

![image](https://github.com/ajalt/mordant/assets/33688601/6cf82800-1c9c-47d0-b191-58604399eca7)

Essentially I want something which looks like your example with static color which does advance without this animation.

![image](https://github.com/ajalt/mordant/assets/33688601/e027dd2a-abdb-457a-a583-71abd15a8bde)

**Comment by ajalt** [comment]
Yes, set `progressbar.pulse` to `false` in your theme flags: `Terminal(theme=Theme { flags["progressbar.pulse"] = false })`.

I'll add more docs for that and add a parameter to the `progressBar` method to allow changing that per-bar.

**Comment by cmdjulian** [comment]
Nice, thx 😊
In the mean time, I get a terminal instance already pre-build by clikt, can I change the setting even when the terminal already is created?

**Comment by ajalt** [comment]
Yes, set it on your context: 
```kotlin
class Tool: CliktCommand() {
    init { context { terminal = Terminal(...) } }
}
```
