### ISSUE TITLE
Implement interactive chooser prompt

### ISSUE THREAD

**Issue by moshenskyi** [ajalt/mordant#133]
Do you plan to implement a selectable chooser like in [Gum](https://github.com/charmbracelet/gum) for bash and some JS CLI libs?

[Example](https://camo.githubusercontent.com/49ac1342e46b65283342eb34fd31ed78ee13fa393a65a01c63966a5bb6c6916e/68747470733a2f2f73747566662e636861726d2e73682f67756d2f63686f6f73652e676966)

**Comment by ajalt** [comment]
This has been asked before in #33 and #89. I don't currently have any plans to add readline/raw mode support to capture keyboard inputs.
