### ISSUE TITLE
Support for target linuxArm64

### ISSUE THREAD

**Issue by vegidio** [ajalt/mordant#155]
Hey, could you please add support for `linuxArm64`?

**Comment by ajalt** [comment]
I don't have an arm device, so I wouldn't be able to test it. Does the [current][1] linux-specific code work without modification on arm? If so, I would be willing to add that target, but if not, I don't want to add platform-specific code that I never run.

[1]: https://github.com/ajalt/mordant/blob/master/mordant/src/linuxMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt

**Comment by JakeWharton** [comment]
If you follow the Kotlin tiers for native, linux ARM must only compile on CI but may not actually work at runtime 😅 

https://kotlinlang.org/docs/native-target-support.html#tier-2

Linux ARM is an important target for embedded and small computing (Raspberry PIs) so I would also suggest it be included.

**Comment by ajalt** [comment]
Good point. We need https://github.com/JetBrains/markdown/issues/146 to publish an arm artifact first, but I'll add it once they do.

**Comment by vegidio** [comment]
Apparently now Markdown has a new artifact with support for `linuxArm64`: https://central.sonatype.com/artifact/org.jetbrains/markdown

**Comment by ajalt** [comment]
I know; I was the one who added it https://github.com/JetBrains/markdown/pull/147 😉

I'm waiting for the next kotest release which adds wasmJs support, then I'll make a release with both new targets. I could of course work around kotest and release now, but they're planning a new release "soon", so I've just been holding off for that.
