### ISSUE TITLE
"The full documentation can be found on the website." link 404's

### ISSUE THREAD

**Issue by aSemy** [ajalt/mordant#158]
When I look on the Mordant docs page https://ajalt.github.io/mordant/, the "The full documentation can be found on the website." links to https://ajalt.github.io/, which 404's

<img width="495" alt="image" src="https://github.com/ajalt/mordant/assets/897017/fc5028b5-33ed-4405-809d-7961a6ea61fe">

**Comment by ajalt** [comment]
Thanks for letting me know!

**Comment by aSemy** [comment]
The link is still 404ing :)
