### ISSUE TITLE
Bug in Multiple Progress Bars example?

### ISSUE THREAD

**Issue by sschuberth** [ajalt/mordant#162]
At https://ajalt.github.io/mordant/progress/#multiple-progress-bars the example calls

    val overall = progress.addTask(overallLayout, total = 100)

which does not pass any `context`. I guess it should be `context = Unit` in that case? Would it make sense to have `context = Unit` as a default argument for `addTask()`?

**Comment by ajalt** [comment]
The example is correct, you need to import [the extension](https://ajalt.github.io/mordant/api/mordant/com.github.ajalt.mordant.animation.progress/add-task.html).

`import com.github.ajalt.mordant.animation.progress.addTask`

**Comment by sschuberth** [comment]
Thanks, that works. Just curious, what's the design decision to make this an extension function instead of providing `context = Unit` by default?

**Comment by ajalt** [comment]
You can't provide a default for a generic type.
