### ISSUE TITLE
Control TerminalInfo for testing

### ISSUE THREAD

**Issue by mikaelstaldal** [ajalt/mordant#170]
I am working with an application which behaves differently depending on values in `TerminalInfo`, and it would be nice to be able to control those for automated integration tests which are run in a separate process started with `java.lang.ProcessBuilder`on JVM. In particular, I need to control `inputInteractive` and `outputInteractive`, but everthing in `TerminalInfo` would be nice to be able to control.

Now `inputInteractive` and `outputInteractive` are false when using a subprocess.

I fetch `TerminalInfo` through CliKi's `CliktCommand.terminal.info`. (Perhaps this should be an issue on CliKt, but would be nice to do the same if you use Mordant without CliKi I guess.)

**Comment by mikaelstaldal** [comment]
Seems like you cannot combine setting Terminal with `context` and `test`, since `test` overrides the Terminal :shrug: 

```
MyCommand().context {
            terminal = Terminal(interactive = true)
        }.test("foo bar")
```

**Comment by ajalt** [comment]
You're right, that needs to be customizable with `test`. That's a clikt issue, though, so I'm closing this one.
