### ISSUE TITLE
MacOs arm64

### ISSUE THREAD

**Issue by vaclavbenes** [ajalt/mordant#180]
Is there any workaround for running this sample code on macOS arm64? In my case, inputs are ignored.

```
fun main() {
    val terminal = Terminal()
    val selection = terminal.interactiveSelectList(
        listOf("Small", "Medium", "Large", "X-Large"),
        title = "Select a Pizza Size",
    )
    if (selection == null) {
        terminal.danger("Aborted pizza order")
    } else {
        terminal.success("You ordered a $selection pizza")
    }
}
```

same stuff working on Linux.
Thx

**Comment by ajalt** [comment]
JVM or native?

**Comment by vaclavbenes** [comment]
Jvm . I didn't try native.

**Comment by ajalt** [comment]
I'm guessing it's the same issue as #86, where JNA just doesn't support macos arm64 well. Maybe a future JNA release will improve that, but really I think the solution is to implement an FFM version of all the syscall code. FFM has its own drawbacks, but at least it should work.

I'll update the docs to mention support.

**Comment by JakeWharton** [comment]
Native is also not working for me. Just doing
```kotlin
fun main() {
  Terminal().interactiveSelectList(listOf("a", "b"))
}
```

**Comment by ajalt** [comment]
> Native is also not working for me. 

Does the list show up but inputs are ignored? Or are you seeing some other problem?

**Comment by JakeWharton** [comment]
Yes it renders properly, it just doesn't respond to any input.
