### ISSUE TITLE
[FR] extend TerminalInfo with utf-8 support

### ISSUE THREAD

**Issue by robstoll** [ajalt/mordant#198]
Would be handy if mordant could also detect if utf-8 support is enabled in the terminal or not

**Comment by ajalt** [comment]
I don't think this is possible to do reliably. Some systems might have some encoding info in an envvar like `LANG`, but I doubt it's always accurate, and I'm sure it's not always present. Mordant also doesn't have any control of the output encoding, so I'd rather leave that up to the system.

**Comment by robstoll** [comment]
Fair enough
