### ISSUE TITLE
awt Color support?

### ISSUE THREAD

**Issue by elect86** [ajalt/mordant#2]
As titled

Would you consider it?

**Comment by ajalt** [comment]
Can you provide more details? I'm not sure what you're asking for.

**Comment by elect86** [comment]
I parametrized the color of some specific debug test and I'd need some sort of static variable..

**Comment by ajalt** [comment]
I'm sorry, it's still not clear what you need from mordant. Maybe provide a code example?

**Comment by elect86** [comment]
Nevermind, I dont need it anymroe

**Comment by elect86** [comment]
I was working on a PR to use gradle kotlin script but you did quicker, nice
