### ISSUE TITLE
Task percentage goes beyond 100% sometimes

### ISSUE THREAD

**Issue by sschuberth** [ajalt/mordant#212]
I'm using [this code](https://github.com/oss-review-toolkit/ort/compare/mordant-downloader-2#diff-74d2cecd7eb6e6fa7a4fb8f057e7d01aed04fab3ef045e311854db0887123f2fR369-R371) to display at most 8 task (plus an overall task) at a time when downloading / verifying an arbitrary number of files (312 in my example):

```kotlin
with(tasks[index % parallelDownloads]) {
    reset { context = pkg to index }
    downloadPackage(pkg, dir, failureMessages)
    advance()
}
```

As you can see, I'm calling `reset` to reuse a given task for display of the progress of the current file, then download, and advance progress. As `reset` sets `completed` to 0 and `advance` increases it by 1, I wonder how it can ever be more than 1, resulting a percentage > 100 as can be seen here:

```
Verifying  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  100%  eta -:--:--
> Package 'Maven:org.glassfish.jaxb:jaxb-core:3.0.2'...                          200%
> Package 'Maven:io.perfmark:perfmark-api:0.26.0'...                             200%
> Package 'NPM:@vue:compiler-dom:3.4.31'...                                      300%
> Package 'NPM:@jridgewell:sourcemap-codec:1.4.15'...                            100%
> Package 'Maven:jakarta.servlet:jakarta.servlet-api:6.1.0'...                   200%
> Package 'Maven:com.google.code.findbugs:jsr305:3.0.2'...                       200%
> Package 'Maven:org.eclipse.angus:angus-activation:2.0.2'...                    200%
> Package 'Maven:org.semver4j:semver4j:5.3.0'...                                 100%
```

**Comment by ajalt** [comment]
you're using limited parallelism, but launching all you async tasks al the same time, so sometimes the same progress task will be run concurrently, causing it to be reset multiple times then advanced multiple times. 

You'll need to do something to ensure that you aren't running multiple asyncs on the same progress task at the same time. Maybe with a queue, or batches or mutexes or something. 

AFAICT, this isn't an issue with mordant.

**Comment by sschuberth** [comment]
> you're using limited parallelism, but launching all you async tasks al the same time

I though that's exactly what limited parallelism tales care of: To work on an arbitrary number of tasks, but only *N* at a time, in a safe manner.

Anyway, that's for the hints!

**Comment by ajalt** [comment]
It is running only N at a time, but there's no guarantees about _which_ N. If you launch 10 asyncs for each progress task, the dispatcher might run all the ones that use the first task at the same time, rather than one from each task like you want. You'll have to enforce the ordering manually.
