### ISSUE TITLE
Current snapshot can't enter raw mode on the JVM

### ISSUE THREAD

**Issue by JakeWharton** [ajalt/mordant#227]
I'm not doing anything special but raw mode no longer works. Seems to get the "dumb" implementation for some reason.

```kotlin
fun main() {
  Terminal().enterRawMode().close()
}
```
```
Exception in thread "main" java.lang.UnsupportedOperationException: Cannot enter raw mode on this system
	at com.github.ajalt.mordant.internal.DumbTerminalInterface.enterRawMode(MppInternal.jvm.kt:165)
	at com.github.ajalt.mordant.input.RawModeKt.enterRawMode(RawMode.kt:19)
	at com.github.ajalt.mordant.input.RawModeKt.enterRawMode$default(RawMode.kt:15)
	at example.MainKt.main(rrtop.kt:14)
```

I am running outside of IntelliJ and Gradle where it should work. Tried with multiple terminal emulators, too, just in case (Warp and Ghostty).

Usung mordant-core 2.7.2.176-SNAPSHOT

**Comment by ajalt** [comment]
If you're getting the `DumbTerminalInterface`, it's not related to the terminal emulator you're running on, it means that there's no usable TerminalInterface on your classpath.

Do you have all the mordant-jvm modules in your dependencies? They should be included by default with the normal `com.github.ajalt.mordant:mordant` target. 

Try adding `implementation("com.github.ajalt.mordant:mordant-jvm-jna:$mordantVersion")` explicitly to see if that fixes it.

**Comment by JakeWharton** [comment]
Oooh I didn't realize I had to pick with 'mordant-core'.

I had to migrate from 'mordant' to 'mordant-core' because 'mordant' no longer appears to be multiplatform. It's `.module` contains only JVM entries. Was it supposed to still be a multiplatform artifact with all variants like it used to be?

**Comment by ajalt** [comment]
Yes, it was supposed to keep working without changes. I'll fix the MPP metadata, and also update that error message to be more helpful.

**Comment by JakeWharton** [comment]
Should those JVM dependencies for the implementation be changed to depend only on 'mordant-core', too?

**Comment by ajalt** [comment]
🤦  Thanks for the heads up. I guess I got carried away with the copy-pasting.

**Comment by JakeWharton** [comment]
Aaaah, yes. That clears up a lot of my own confusion browsing around!
