### ISSUE TITLE
Request terminal features to be included in Java standard library

### ISSUE THREAD

**Issue by mikaelstaldal** [ajalt/mordant#235]
It's unfortunate that Mordant requires native library on JVM, but currently unavoidable.

Maybe it would be good to request these features (check for interactivity, query terminal size, enter raw mode, anything else needed?) to be added to Java standard library.

Should be fairly easy to implement there given that some of this is already provided by [java.io.Console](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/io/Console.html). I would guess that [Console.readPassword()](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/io/Console.html#readPassword()) needs to enter raw mode, and that [System.console()](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/System.html#console()) checks for interactivity.

**Comment by ajalt** [comment]
You're welcome to make requests to the Java committee, but that's out of scope for this library, so I'll close this issue.
