### ISSUE TITLE
please document platform constraints

### ISSUE THREAD

**Issue by NikkyAI** [ajalt/mordant#24]
i am new to mordant (and i love it)
but yesterday i tried to add a animation and a progress bar (because i saw them i nthe README)
just to discover that they are JVM only and not available in common code (we target jvm, linux and mingw)

something like the colored platform tags in the kotlin docs would help a lot with figuring outif a feature is available
![tags](https://nikky.catgirl.host/i/bn7ep0p8.png)

**Comment by ajalt** [comment]
I updated the README and added dokka API docs that contain platform tags. I'll write more comprehensive documentation in the future.
