### ISSUE TITLE
Mordant 2.0 terminal capabilities

### ISSUE THREAD

**Issue by fabriziofortino** [ajalt/mordant#26]
I have some markdown with a link in a table cell.

It works great on iTerm2 but not on the Apple Terminal (the entire URL is shown).

Not sure this is a Mordant issue. If not, it would be nice to have a function that says if a component is not supported on the current terminal.

**Comment by ajalt** [comment]
[`Terminal.info`])(https://ajalt.github.io/mordant/api/mordant/com.github.ajalt.mordant.terminal/-terminal/info.html) shows what capabilities mordant has detected based on the current environment. 

Does Apple Terminal support hyperlinks? I was under the impression that it doesn't. I don't have a mac to test myself, but you can force mordant to emit ansi hyperlink codes by passing `hyperlinks=true` to the `Terminal` constructor. If the hyperlinks work, than we can update mordant's support list (please run `echo TERM=$TERM TERM_PROGRAM=$TERM_PROGRAM TERM_PROGRAM_COMMAND=$TERM_PROGRAM_COMMAND`, and send me the output).

If App Terminal doesn't support hyperlinks, than Mordant is working correctly.

**Comment by fabriziofortino** [comment]
Apple Terminal does not support hyperlinks. So Mordant is working as expected. I was looking for the flag to understand when hyperlinks can be used or not. `Terminal.info.ansiHyperLinks` is what I was looking for. Thanks
