### ISSUE TITLE
Can we support Kotlin/Native for this library?

### ISSUE THREAD

**Issue by wuseal** [ajalt/mordant#3]
As the title said, can we make this library fit KMPP?, Then I can use this library to develop a command-line tool that could run without JVM on any Platform, Like MacOSX Linux and Windows. 😄

**Comment by ajalt** [comment]
It's definitely something I plan to do, although I don't have a timeline.

**Comment by GGorAA** [comment]
+, we really need this library for Kotlin/Native!

**Comment by manuelprinz** [comment]
Hi @ajalt, I really love this library (and Clikt)! I'm also interested in Native support. Although I do not have that much experience with it on the library side of things, I experimented a bit to get at least the setup working. The idea was to move as much as possible to `common{Main,Test}` eventually and identify the issues on the way. The results can be found [here](https://github.com/manuelprinz/mordant/tree/kotlin-native-linux), although nothing besides running a simple test works right now. I still have to familiarize myself with the code.

I am not sure if or how I can help. I've joined the Kotlin Slack, feel free to get in touch if you'd like to discuss how to go about it.

**Comment by ajalt** [comment]
@manuelprinz, MPP support for all platforms will be part of 2.0 (#8), I'm just waiting for the upstream markdown library to be published with the native support I contributed (https://github.com/valich/intellij-markdown/pull/59). 

I don't need any help coding this particular capability, but I'd love feedback on features, API design, or your use case if you want to share it.

**Comment by manuelprinz** [comment]
I am interested in using it on a small CLI tool (using Clikt) to fetch and display data from a REST API with Kotlin/Native, so the table feature is something I am interested in. I'll do some more experiments and update #8. Thanks!

**Comment by DrewCarlson** [comment]
I also need mordant for a cli tool that formats data from an API.  [Here](https://dl.bintray.com/drewcarlson/mordant/) I've published mordant `2.0.0-mpp` and markdown `0.2.0.pre-mpp` for `jvm`, `linuxX64`, and `macosX64`. See https://github.com/ajalt/mordant/pull/9

**Comment by ajalt** [comment]
Version 2.0.0-beta1 has been released with mingwX64 and linuxX64 native targets. macosX64 will be added in the future. Try it out and let me know if you run into any issues!
