### ISSUE TITLE
Mordant 2.0: interactive list support

### ISSUE THREAD

**Issue by fabriziofortino** [ajalt/mordant#33]
It would be nice to have a Widget to support the interactive selection of items from a list.

Something similar to this:
https://github.com/DmitryBogomolov/cli-list-select

**Comment by ajalt** [comment]
It would be straightforward to make a widget to display a list like that, but Mordant doesn't currently have any readline support, so making it interactive would require target-specific code. Although it would be nice to add support for raw mode, reading key presses etc., given the limitations of the JVM, I don't currently have plans to do so.

**Comment by russellbanks** [comment]
I've achieved this using JLine to enter raw mode and update an animation accordingly. [Here](https://github.com/russellbanks/Komac/blob/main/src/main/kotlin/utils/MenuCreator.kt) is my implementation.
