### ISSUE TITLE
Animation could overdraw instead of clear to avoid flicker

### ISSUE THREAD

**Issue by mikehearn** [ajalt/mordant#40]
When rendering an animation at high speed there is unfortunately some ugly flicker in most terminals. I suspect the cause is that `Animation` starts by clearing the space previously used. This is nice and simple but causes flicker. For a flicker-free experience, text should be emitted that covers the entire previous area so clearing isn't used at all.

Perhaps a simple optimization would be to notice when the size of the rendered widget hasn't changed and just skip the clear, or allow animations to opt-in to that when they know that their rendered widget will always overdraw everything anyway?

**Comment by ajalt** [comment]
I think that's a good idea, and should be easy to implement.

I haven't personally seen any flickering in the animations I've used. Would you be able to share some more information on your setup, and an example of the animations you're using if possible?

**Comment by mikehearn** [comment]
Hmm interesting. I might be using Mordant wrong, or using it more aggressively.

I recorded an asciinema of my upcoming product, which uses Mordant primarily for tables and progress bars. It's here:

https://asciinema.org/a/inaU21bRpfhdj97v8MXKoktxh

Interestingly, asciinema playback captures the flickering in exactly the same way as I see in iTerm2. So I think the issue is real. Originally I figured terminals should be able to avoid it because the clear codes are written out in the same write as everything else. Apparently not.

**Comment by ajalt** [comment]
Thanks for the recording. If you're able to share a minimized code example of how you're generating that animation, I might be able to provide some insight into whether you're using it wrong or not.

Either way, I'll definitely implement this optimization.

**Comment by mikehearn** [comment]
Is there somewhere I can get your email address? I can email you the file - it's fairly self contained (but not completely). You wouldn't be able to compile it but all the animation/Mordant relevant code would be there.

**Comment by ajalt** [comment]
I think that would still be helpful. I don't want to post my email publicly, but you can DM me on ASG or kotlinlang slack.
