### ISSUE TITLE
Demo Terminal.textAnimation with 256 colors produces an IllegalArgumentException

### ISSUE THREAD

**Issue by OliverO2** [ajalt/mordant#41]
**Version: 2.0.0-beta3**

Running the demo animation on a 256-color terminal...
```kotlin
        val t = Terminal(ansiLevel = AnsiLevel.ANSI256)
        val a = t.textAnimation<Int> { frame ->
            (1..50).joinToString("") {
                val hue = (frame + it) * 3 % 360
                t.colors.hsv(hue, 100, 100)("━")
            }
        }

        t.cursor.hide(showOnExit = true)
        repeat(120) {
            a.update(it)
            Thread.sleep(25)
        }
```

...produces this exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Spans cannot contain ANSI codes
        at com.github.ajalt.mordant.rendering.Span$Companion.word(Span.kt:22)
        at com.github.ajalt.mordant.internal.ParsingKt.splitLines(Parsing.kt:90)
        at com.github.ajalt.mordant.internal.ParsingKt.parseText(Parsing.kt:23)
        at com.github.ajalt.mordant.widgets.Text.<init>(Text.kt:29)
        at sca.Application$run$$inlined$textAnimation$default$1.renderData(Animation.kt:89)
        at com.github.ajalt.mordant.animation.Animation.update(Animation.kt:60)
[...]
```

It appears that an escape sequence containing a negative parameter is produced (escape character replaced by `E` for readability):
`E[38;5;-313484m`

Negative values seem to appear initially in the conversion of `HSV(h=3.0, s=100.0, v=100.0, alpha=1.0)` to `SRGB` in `ajalt/colormath/model/HSV.kt` (with `h` normalized to `0.05`):
```kotlin
    override fun toSRGB(): RGB {
        if (s < 1e-7) return RGB(v, v, v, alpha)
        val v = v.toDouble()
        val h = (h.normalizeDeg() / 60.0)
        val s = s.toDouble()

        fun f(n: Int): Float {
            val k = (n + h) % 6
            return (v - v * s * minOf(k, 4 - k, 1.0).coerceAtLeast(0.0)).toFloat()
        }
        return SRGB(f(5), f(3), f(1), alpha)
    }
```

It returns `SRGB(r=100.0, g=-9400.0 b=-9900.0 alpha=1.0)`.

I did not dive into the underlying math, but hopefully this helps.

**Comment by ajalt** [comment]
So the negative values in the conversion are because colormath's [HSV is scaled to 0-1][1]. So you should use `t.colors.hsv(hue, 1, 1)` instead of `hsv(hue, 100, 100)`. 

But either way, mordant should clamp ANSI values to the sRGB gamut to avoid this exception.

[1]: https://ajalt.github.io/colormath/colorspaces/#hsv

**Comment by OliverO2** [comment]
Thanks, good to know! Note that I've copied the code directly from https://github.com/ajalt/mordant#animations.

So it would probably be a good idea to correct the example, and add some `require` statements in `hsv()` and others in mordant and colormath to catch invalid parameters early.

**Comment by ajalt** [comment]
Yes, I think that's a good idea. colormath deliberately allows out-of-gamut colors, but mordant could definitely add those checks.
