### ISSUE TITLE
Support animations in non-interactive consoles

### ISSUE THREAD

**Issue by anogma** [ajalt/mordant#49]
Some IDEs have partial ANSI support. They know how to interpret color codes but can't change the cursor position. Fortunately, they understand carriage returns (CR). So, it's possible for them to support some animations if we don't print line feeds.

The logic behind the animation loop seems to be: do a carriage return, then move the cursor up by one line and finally print the animation ending with a line feed. What if we don't print that line feed?

**Comment by ajalt** [comment]
Can you give me an example of the IDEs you're trying to run animations in, and the animation you'd like to use?

**Comment by anogma** [comment]
I'm using Intellij IDEA. I'd like to use the progress animation.

**Comment by ajalt** [comment]
Should be fixed in 2.0.0-beta5
