### ISSUE TITLE
Custom color for borders of table

### ISSUE THREAD

**Issue by yamin8000** [ajalt/mordant#50]
is there any way to change the table's border color?

**Comment by ajalt** [comment]
Yes: Set the [borderTextStyle][1] in your table builder.

```kotlin
table {
    borderTextStyle = red
}
```
[1]: https://ajalt.github.io/mordant/api/mordant/com.github.ajalt.mordant.table/-table-builder/index.html#-2072221089%2FProperties%2F-1759575997

**Comment by yamin8000** [comment]
> Yes: Set the [borderTextStyle](https://ajalt.github.io/mordant/api/mordant/com.github.ajalt.mordant.table/-table-builder/index.html#-2072221089%2FProperties%2F-1759575997) in your table builder.
> 
> ```kotlin
> table {
>     borderTextStyle = red
> }
> ```

Confusing name IMHO, I thought that was for the text. BTW thank you.  your lib is great.

**Comment by ajalt** [comment]
I'm open to suggestions for a better name.

My reasoning for this one is that the name `borderStyle` is already used for setting the characters that make up the border, and `borderTextStyle` sets the `TextStyle` for the border.

**Comment by yamin8000** [comment]
> I'm open to suggestions for a better name.
> 
> My reasoning for this one is that the name `borderStyle` is already used for setting the characters that make up the border, and `borderTextStyle` sets the `TextStyle` for the border.

You can rename `borderStyle` to `borderType` and `borderTextStyle` to `borderStyle` but maybe that would defeat the possibility of that borders can be characters (text) that can have style (bold/italic/underline/colors/etc).
