### ISSUE TITLE
IntelliJ detection misfires if the program has a command line containing the word "idea"

### ISSUE THREAD

**Issue by mikehearn** [ajalt/mordant#72]
This line in `TerminalDetection.kt`:

`getJavaProperty("sun.java.command")?.contains("idea", ignoreCase = true) == true`

will cause terminal corruption if you run a program with the word "idea" anywhere in the command line arguments. (yup, debugging this one was fun 😆 ). I filed https://github.com/JetBrains/jediterm/issues/253 to request a specific env var to be set, but for now, the `sun.java.command` check should probably be removed. The others look fairly specific but this one is too broad and will cause obscure bugs for any tool that is used on files in the default IntelliJ project directory (e.g. `~/IdeaProjects`).

**Comment by ajalt** [comment]
Hm. That check is the only one that works on recent versions of IntelliJ, but I don't think we need to need to remove that check entirely. We could make it more specific by just looking at the binary name rather then the full path. I think it's unlikely that anyone will name their commands `idea64.exe`, for example.

**Comment by mikehearn** [comment]
I think the issue is that sun.java.command contains the CLI arguments, and sometimes not even the program name at all. IIRC this property is what gets printed by `jps -v` and what I see is that the IDEA processes don't actually even have a program name, just the flags, and others use the main class name as the binary name.

**Comment by ajalt** [comment]
Ok, I went ahead and removed that check. Thanks for tracking the problem down!
